blank_issues_enabled: true
contact_links:
  - name: World Wide METAVERSE 
    url: https://t.me/WorldWide_METAVERSE
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: 
    about: Documentation for getting started with bot.
